version: "3.4"

services:

  proxy:
    image: nginxproxy/nginx-proxy
    container_name: ocms-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - proxynet

  webserver:
    environment:
      - VIRTUAL_HOST=localhost
      - CERT_NAME=localhost
    networks:
      - proxynet

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - proxynet

  mysql:
    container_name: ocms-mysql
    image: mysql:8.0
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - proxynet

  phpmyadmin:
    container_name: ocms-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=db.localhost
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=
    networks:
      - proxynet
    depends_on:
      - proxy
      - mysql

#  solr:
#    image: solr:8.9.0
#    container_name: ocms-solr
#    ports:
#      - "8983:8983"
#    volumes:
#      - search-data:/var/solr
#    command:
#      - solr-precreate
#      - gettingstarted
#    environment:
#      - VIRTUAL_HOST=search.localhost
#    networks:
#      - proxynet
#    depends_on:
#      - proxy

  php-fpm:
    container_name: ocms-php-fpm
    build:
      target: testing
    networks:
      - proxynet

networks:
  proxynet:
    external: false

volumes:
  search-data:
