version: "3.4"

services:

  proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx-server
    working_dir: /application
    volumes:
      - ./app:/application:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      args:
        composer_user: toor
        user: www-data
        group: www-data
        uid: 1000
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: hoopless-php-fpm
    working_dir: /application
    volumes:
      - ./app:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
